<!DOCTYPE html>
<html lang="ko-kr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Erlang &amp; Go  | Elixir try, catch and rescue (#19/21)</title>
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <meta name="generator" content="Hugo 0.51" />
    
    
      <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    

    
    
      <link href="/dist/css/app.e08a958ae3e530145318b6373195c765.css" rel="stylesheet">
    

    

    
      
    

    

    <meta property="og:title" content="Elixir try, catch and rescue (#19/21)" />
<meta property="og:description" content="본 문서는 elixir-lang.org의 Getting Started문서의 한글 번역본입니다.
자세한 내용은 원문을 참조해 주세요.
 elixir는 세 개의 에러 매커니즘을 갖는다: errors, throws, exits. 이번 챕터에서 우리는 이들 각각을 살펴보도록 한다.
Errors 에러(또는 예외)는 코드에서 예외적인 상황이 발생할 때 사용된다. 숫자를 atom에 더할 때 발생할 수 있는 에러를 살펴보자.
 iex&gt; :foo &#43; 1 ** (ArithmeticError) bad argument in arithmetic expression :erlang.&#43;(:foo, 1)  raise/1 함수를 사용하면 아무 때나 런타임에 에러를 발생시킬 수 있다." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://jeidee.github.io/2015/06/19/elixir-try-catch-and-rescue-1921/" /><meta property="article:published_time" content="2015-06-19T00:00:00&#43;00:00"/>
<meta property="article:modified_time" content="2015-06-19T00:00:00&#43;00:00"/>

<meta itemprop="name" content="Elixir try, catch and rescue (#19/21)">
<meta itemprop="description" content="본 문서는 elixir-lang.org의 Getting Started문서의 한글 번역본입니다.
자세한 내용은 원문을 참조해 주세요.
 elixir는 세 개의 에러 매커니즘을 갖는다: errors, throws, exits. 이번 챕터에서 우리는 이들 각각을 살펴보도록 한다.
Errors 에러(또는 예외)는 코드에서 예외적인 상황이 발생할 때 사용된다. 숫자를 atom에 더할 때 발생할 수 있는 에러를 살펴보자.
 iex&gt; :foo &#43; 1 ** (ArithmeticError) bad argument in arithmetic expression :erlang.&#43;(:foo, 1)  raise/1 함수를 사용하면 아무 때나 런타임에 에러를 발생시킬 수 있다.">


<meta itemprop="datePublished" content="2015-06-19T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2015-06-19T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="808">



<meta itemprop="keywords" content="tutorial," />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Elixir try, catch and rescue (#19/21)"/>
<meta name="twitter:description" content="본 문서는 elixir-lang.org의 Getting Started문서의 한글 번역본입니다.
자세한 내용은 원문을 참조해 주세요.
 elixir는 세 개의 에러 매커니즘을 갖는다: errors, throws, exits. 이번 챕터에서 우리는 이들 각각을 살펴보도록 한다.
Errors 에러(또는 예외)는 코드에서 예외적인 상황이 발생할 때 사용된다. 숫자를 atom에 더할 때 발생할 수 있는 에러를 살펴보자.
 iex&gt; :foo &#43; 1 ** (ArithmeticError) bad argument in arithmetic expression :erlang.&#43;(:foo, 1)  raise/1 함수를 사용하면 아무 때나 런타임에 에러를 발생시킬 수 있다."/>

  </head>

  <body class="ma0 avenir bg-near-white">

    
   
  

  <header>
    <div class="bg-black">
      <nav class="pv3 ph3 ph4-ns" role="navigation">
  <div class="flex-l justify-between items-center center">
    <a href="https://jeidee.github.io/" class="f3 fw2 hover-white no-underline white-90 dib">
      Erlang &amp; Go
    </a>
    <div class="flex-l items-center">
      
      









    </div>
  </div>
</nav>

    </div>
  </header>



    <main class="pb7" role="main">
      
  
  <article class="flex-l flex-wrap justify-between mw8 center ph3 ph0-l">

    <header class="mt4 w-100">
      <p class="f6 b helvetica tracked">
          
        POSTS
      </p>
      <h1 class="f1 athelas mb1">Elixir try, catch and rescue (#19/21)</h1>
      
      <time class="f6 mv4 dib tracked" datetime="2015-06-19T00:00:00Z">June 19, 2015</time>      
      
      
    </header>

    <main class="nested-copy-line-height lh-copy serif f4 nested-links nested-img mid-gray pr4-l w-two-thirds-l">

<blockquote>
<p>본 문서는 elixir-lang.org의 <a href="http://elixir-lang.org/getting-started/introduction.html">Getting Started</a>문서의 한글 번역본입니다.</p>

<p>자세한 내용은 원문을 참조해 주세요.</p>
</blockquote>

<p>elixir는 세 개의 에러 매커니즘을 갖는다: errors, throws, exits. 이번 챕터에서 우리는 이들 각각을 살펴보도록 한다.</p>

<h2 id="errors">Errors</h2>

<p>에러(또는 예외)는 코드에서 예외적인 상황이 발생할 때 사용된다. 숫자를 atom에 더할 때 발생할 수 있는 에러를 살펴보자.</p>

<pre><code>  
iex&gt; :foo + 1
  
** (ArithmeticError) bad argument in arithmetic expression
       
:erlang.+(:foo, 1)
  
</code></pre>

<p>raise/1 함수를 사용하면 아무 때나 런타임에 에러를 발생시킬 수 있다.</p>

<pre><code>  
iex&gt; raise &quot;oops&quot;
  
** (RuntimeError) oops
  
</code></pre>

<p>raise/2함수를 사용하면 에러명과 키워드 리스트를 매개변수로 넘겨 다른 에러를 발생시킬 수 있다.</p>

<pre><code>  
iex&gt; raise ArgumentError, message: &quot;invalid argument foo&quot;
  
** (ArgumentError) invalid argument foo
  
</code></pre>

<p>우리는 우리의 모듈에서 defexception을 사용해 우리만의 에러를 정의할 수 있다. 이 방법을 사용하면 에러이름이 모듈명과 동일해진다. 일반적인 방법은 메세지 필드와 함께 커스텀 예외를 정의하는 것이다.</p>

<pre><code>  
iex&gt; defmodule MyError do
  
iex&gt; defexception message: &quot;default message&quot;
  
iex&gt; end
  
iex&gt; raise MyError
  
** (MyError) default message
  
iex&gt; raise MyError, message: &quot;custom message&quot;
  
** (MyError) custom message
  
</code></pre>

<p>try/rescue 구문을 사용하면 에러를 처리할 수 있다.</p>

<pre><code>  
iex&gt; try do
  
&amp;#8230;&gt; raise &quot;oops&quot;
  
&amp;#8230;&gt; rescue
  
&amp;#8230;&gt; e in RuntimeError -&gt; e
  
&amp;#8230;&gt; end
  
%RuntimeError{message: &quot;oops&quot;}
  
</code></pre>

<p>위의 예제는 런타임 에러를 처리하며 iex 세션에 에러 자체를 출력한다. 실제로는, try/rescue 구문은 드물게 사용된다. 예를 들어, 많은 언어에서 파일이 성공적으로 열리지 않았을 경우 에러를 발생하고 처리하도록 한다. elixir는 그 대신에 파일을 연후 그 결과를 튜플로 반환하는 File.read/1 함수를 제공한다.</p>

<pre><code>  
iex&gt; File.read &quot;hello&quot;
  
{:error, :enoent}
  
iex&gt; File.write &quot;hello&quot;, &quot;world&quot;
  
:ok
  
iex&gt; File.read &quot;hello&quot;
  
{:ok, &quot;world&quot;}
  
</code></pre>

<p>여기에서 try/rescue를 사용하진 않았다. 우리가 파일을 열었을 때 발생하는 여러 상황을 처리하길 원한다면, 단순히 case 구문을 사용하면 된다.</p>

<pre><code>  
iex&gt; case File.read &quot;hello&quot; do
  
&amp;#8230;&gt; {:ok, body} -&gt; IO.puts &quot;Success: #{body}&quot;
  
&amp;#8230;&gt; {:error, reason} -&gt; IO.puts &quot;Error: #{reason}&quot;
  
&amp;#8230;&gt; end
  
</code></pre>

<p>언젠가, 파일을 열때 예외를 발생할지 말지 결정해야할 때가 올 것이다. 이것이 바로 elixir가 File.read/1과 그 외의 많은 함수에서 예외를 발생시키지 않는 이유이다. 대신에, 개발자가 스스로 최선의 처리를 하도록 해 준다.</p>

<p>파일이 존재하길 기대하는 경우라면(없을 경우 에러가 발생해야만 하는 경우) 우리는 단순히 File.read!/1 함수를 사용하면 된다.</p>

<pre><code>  
iex&gt; File.read! &quot;unknown&quot;
  
** (File.Error) could not read file unknown: no such file or directory
      
(elixir) lib/file.ex:305: File.read!/1
  
</code></pre>

<p>표준 라이브러리의 많은 함수가 이러한 패턴(에러를 발생시키는 함수와 튜플을 반환하는 함수를 쌍으로 갖는)을 따른다. 이러한 관습에 따라 foo 함수와 foo! 함수는 각각 예외 없이 튜플을 반환하거나 실패할 경우 에러를 발생시키는 방식으로 구현되어 있다. File 모듈이 이러한 관습의 대표적인 예이다.</p>

<p>elixir에서 우리는 흐름 제어를 위해 try/rescue 구문을 사용하지 않는 것이 좋다. 에러는 글자 그대로 에러로 취급해야 한다. 즉, 에러는 기대하지 않은 상황이며 예외적인 상황에 사용됨을 확실히 하는 것이다. 흐름 제어가 필요하다면, throws를 사용해라.</p>

<h2 id="throws">Throws</h2>

<p>elixir에서 값을 던져서 나중에 받을 수 있다. throw와 catch는 이와 같은 상황에서 사용되는 구문이다.</p>

<p>이런 상황은 적합한 API를 제공하지 않는 라이브러리와 인터페이스하는 경우를 제외하고는 실제로 흔하지 않다. 예를 들어, Enum 모듈이 값을 찾는 API를 제공하지 않는 상황에서 숫자 리스트에서 13의 첫 번째 배수를 찾는다고 가정해 보자.</p>

<pre><code>  
iex&gt; try do
  
&amp;#8230;&gt; Enum.each -50..50, fn(x) -&gt;
  
&amp;#8230;&gt; if rem(x, 13) == 0, do: throw(x)
  
&amp;#8230;&gt; end
  
&amp;#8230;&gt; &quot;Got nothing&quot;
  
&amp;#8230;&gt; catch
  
&amp;#8230;&gt; x -&gt; &quot;Got #{x}&quot;
  
&amp;#8230;&gt; end
  
&quot;Got -39&quot;
  
</code></pre>

<p>Enum은 적합한 API를 제공하기 때문에, 사실 Enum.find/2는 잘 동작할 것이다.</p>

<pre><code>  
iex&gt; Enum.find -50..50, &amp;(rem(&amp;1, 13) == 0)
  
-39
  
</code></pre>

<h2 id="exits">Exits</h2>

<p>모든 elixir 코드는 서로 통신하는 프로세스 안에서 실행된다. 프로세스가 &#8220;자연스럽게 야기된 오류 &#8211; natural causes&#8221;로 죽는다면(예를 들면 처리되지 않은 예외같은), 프로세스는 exit 시그널을 보낸다. 프로세스는 exit 시그널을 명시적으로 보내는 것으로 죽을 수도 있다.</p>

<pre><code>  
iex&gt; spawn_link fn -&gt; exit(1) end
  
#PID&lt;0.56.0&gt;
  
** (EXIT from #PID&lt;0.56.0&gt;) 1
  
</code></pre>

<p>위의 예제에서, 연결된 프로세스는 1의 값을 갖는 exit 시그널을 보내는 것에 의해 죽게된다. elixir는 자동적으로 해당 메세지를 처리하고 터미널에 결과를 출력한다.</p>

<p>exit는 try/catch 구문에서 처리될 수 있다.</p>

<pre><code>  
iex&gt; try do
  
&amp;#8230;&gt; exit &quot;I am exiting&quot;
  
&amp;#8230;&gt; catch
  
&amp;#8230;&gt; :exit, _ -&gt; &quot;not really&quot;
  
&amp;#8230;&gt; end
  
&quot;not really&quot;
  
</code></pre>

<p>try/catch를 사용하는 것도 드물지만 exit를 처리하는 것도 매우 드문 경우이다.</p>

<p>exit 시그널은 Erlang VM에 의해 제공되는 결함 내구성(fault-tolerant) 시스템의 부분으로서 아주 중요하다. 프로세스는 일반적으로 감독되는 프로세스로 부터 exit 시그널을 기다리는 슈퍼비전 트리 안에서 실행된다. exit 시그널을 한 번 받으면, 슈퍼바이저 전략에 의해 kick된 후 곧 바로 재시작 된다.</p>

<p>이것이 바로 elixir에서 try/catch, try/rescue가 일반적이지 않은 이유이다. 에러를 처리(복구)하는 대신, &#8220;빨리 실패-fail fast&#8221;하고, 슈퍼비전 트리에서 에러가 없는 초기 상태로 재빨리 복구되도록 보장하는 것이 더 중요하다.</p>

<h2 id="after">After</h2>

<p>때때로, 에러가 발생할 수 있는 잠재적인 어떤 액션 이후에 리소스를 깨끗이 비워지도록 하는 것이 필요하다. try/after 구문은 우리가 이러한 처리를 할 수 있도록 해 준다. 예를 들어, 우리가 파일을 열고 항상 닫히길 원한다면 try/after 구문을 사용하면 된다.</p>

<pre><code>  
iex&gt; {:ok, file} = File.open &quot;sample&quot;, [:utf8, :write]
  
iex&gt; try do
  
&amp;#8230;&gt; IO.write file, &quot;olá&quot;
  
&amp;#8230;&gt; raise &quot;oops, something went wrong&quot;
  
&amp;#8230;&gt; after
  
&amp;#8230;&gt; File.close(file)
  
&amp;#8230;&gt; end
  
** (RuntimeError) oops, something went wrong
  
</code></pre>

<h2 id="varialbes-scope">Varialbes scope</h2>

<p>try/catch/rescue/after 블럭 안에서 사용된 변수가 문맥 밖으로 누출되지 않게 하는 것은 매우 중요하다. 변수가 처음 바인드 되기 전에 try 블록에서 실패하게 되는 상황때문이다. 달리 말해, 코드가 유효하지 않게 되는 것이다.</p>

<pre><code>  
iex&gt; try do
  
&amp;#8230;&gt; from_try = true
  
&amp;#8230;&gt; after
  
&amp;#8230;&gt; from_after = true
  
&amp;#8230;&gt; end
  
iex&gt; from_try
  
** (RuntimeError) undefined function: from_try/0
  
iex&gt; from_after
  
** (RuntimeError) undefined function: from_after/0
  
</code></pre>

<h2 id="참고">참고</h2>

<ul>
<li><a href="http://elixir-lang.org/getting-started/try-catch-and-rescue.html">Elixir try, catch and rescue</a></li>
</ul>
<ul class="pa0">
  
   <li class="list">
     <a href="/tags/tutorial" class="link f5 grow no-underline br-pill ba ph3 pv2 mb2 dib black sans-serif">tutorial</a>
   </li>
  
</ul>
<div class="mt6">
        <div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "https-erlnote-wordpress-com" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
      </div>
    </main>

    <aside class="w-30-l mt6-l">




  <div class="bg-light-gray pa3 nested-list-reset nested-copy-line-height nested-links">
    <p class="f5 b mb3">Related</p>
    <ul class="pa0 list">
	   
	     <li  class="mb2">
          <a href="/2015/06/19/elixir-sigils-1821/">Elixir Sigils (#18/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/18/elixir-protocols-1621/">Elixir Protocols (#16/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/18/elixir-comprehensions-1721/">Elixir Comprehensions (#17/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/17/elixir-module-attributes-1421/">Elixir Module attributes (#14/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/17/elixir-io-and-the-file-system-1221/">Elixir IO and the file system (#12/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/17/elixir-structs-1521/">Elixir Structs (#15/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/17/elixir-alias-require-and-import-1321/">Elixir alias, require and import (#13/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/16/elixir-processes-1121/">Elixir Processes (#11/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/15/elixir-enumerables-and-streams-1021/">Elixir Enumerables and Streams (#10/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/12/elixir-modules-821/">Elixir Modules (#8/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/12/elixir-keywords-maps-and-dicts-721/">Elixir Keywords, maps and dicts (#7/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/12/elixir-binaries-strings-and-char-lists-621/">Elixir Binaries, strings and char lists (#6/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/12/elixir-recursion-921/">Elixir Recursion (#9/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/11/elixir-pattern-matching-421/">Elixir Pattern matching (#4/21)</a>
        </li>
	    
	     <li  class="mb2">
          <a href="/2015/06/11/elixir-case-cond-and-if-521/">Elixir case, cond and if (#5/21)</a>
        </li>
	    
    </ul>
</div>

</aside>

  </article>

    </main>
    <footer class="bg-black bottom-0 w-100 pa3" role="contentinfo">
  <div class="flex justify-between">
  <a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href="https://jeidee.github.io/" >
    &copy; 2018 Erlang &amp; Go
  </a>
    <div>








</div>
  </div>
</footer>

    

  <script src="/dist/js/app.3fc0f988d21662902933.js"></script>


  </body>
</html>
